image: node:9-alpine

stages:
  - test

test:
  stage: test
  services:
    - mongo:latest
  script:
    - npm i npm@latest -g
    - npm i
    - PORT=5080 DB=mongodb://mongo:27017/contactdb node server.js &
    - apk update && apk add ca-certificates && update-ca-certificates && apk --no-cache add openssl wget
    - wget -O vrest_ng_cli -q https://github.com/Optimizory/vrest-ng-cli/releases/download/v1.0.1/vrest_ng_cli_linux_1_0_1
    - ls -ltr
    - chmod +x ./vrest_ng_cli
    - vrest_ng_cli run 