image: node:9-alpine

stages:
  - test

# Cache modules in between jobs
cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
  - node_modules/

test:
  stage: test
  services:
    - mongo:latest
  script:
    - npm i npm@latest -g
    - npm i
    - PORT=5090 node server.js &
    - apk update && apk add ca-certificates && update-ca-certificates && apk --no-cache add openssl wget
    - wget -O vrest_ng_cli -q https://github.com/Optimizory/vrest-ng-cli/releases/download/v1.0.1/vrest_ng_cli_alpine_1_0_1
    - chmod u+x ./vrest_ng_cli
    - ./vrest_ng_cli run --projectdir=./test/scenario-tests --logger=xunit
  artifacts:
    when: always
    paths:
      - vrest_logs/logs.xml
    reports:
      junit: vrest_logs/logs.xml