# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'
# NPM modules and Cypress binary should be cached
# otherwise the install will be too slow
# https://docs.microsoft.com/en-us/azure/devops/pipelines/caching/?view=azure-devops
# since the username / user home directory are not available via system variables
# (there is even an open question about it)
# https://docs.microsoft.com/en-us/azure/devops/pipelines/build/variables?view=azure-devops
# just use "/home/vsts" for now
- task: CacheBeta@1
  inputs:
    key: npm | $(Agent.OS) | package-lock.json
    path: /home/vsts/.npm
    restoreKeys: npm | $(Agent.OS) | package-lock.json
  displayName: Cache NPM packages
- task: CacheBeta@1
  inputs:
    key: vrest | $(Agent.OS) | package-lock.json
    path: /home/vsts/.cache/vrest
    restoreKeys: vrest | $(Agent.OS) | package-lock.json
  displayName: Cache vrest-ng-cli binary

- script: npm install
  displayName: 'Install NPM dependencies'

- script: npm install -g vrest-ng-cli
  displayName: 'Install vrest-ng-cli'

- script: vrest-ng-cli run --projectdir=test/scenario-tests --logger=xunit
  displayName: 'Run vREST NG Tests'

# Publish Test Results
# Publish test results to Azure Pipelines
- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'xUnit' # Options: JUnit, NUnit, VSTest, xUnit, cTest
    testResultsFiles: 'vrest_logs/log.xml' 
    searchFolder: '$(System.DefaultWorkingDirectory)' # Optional

